compile: prog6.c
	gcc -Wall -g prog6.c -o prog6
test: prog6.c
	./prog6 USC.bmp USCOut.bmp +63 -17 +0
run: prog6.c
	gcc -Wall -g prog6.c -o prog6
	./prog6 Tiger.bmp TigerOut.bmp +63 -17 +0
test2:
	gcc -Wall -g prog6.c -o prog6
	./prog6 CU.bmp CUOut.bmp +63 -17 +0
name:
	gcc -Wall -g prog6.c -o prog6
	./prog6 Tiger.bmp Tiger.bmp +63 -17 +0
arg:
	gcc -Wall -g prog6.c -o prog6
	./prog6 Tiger.bmp TigerOut.bmp +63 -17 +0 +98
val:
	gcc -Wall -g prog6.c -o prog6
	./prog6 Tiger.bmp TigerOut.bmp +63 -201 +0
