compile: prog5.c
	gcc -Wall -g prog5.c -o prog5
test: prog5 textTest.txt
	./prog5 textTest.txt Output.txt Dictionary.txt
run:
	gcc -Wall -g prog5.c -o prog5
	./prog5 "There's_Something_In_These_Hills.txt" Output.txt Dictionary.txt

run2:
	gcc -Wall -g prog5.c -o prog5
	./prog5 USConstitution.txt Output.txt Dictionary.txt
